{"ast":null,"code":"import { createErrorClass } from './createErrorClass';\nexport var SequenceError = createErrorClass(function (_super) {\n  return function SequenceErrorImpl(message) {\n    _super(this);\n    this.name = 'SequenceError';\n    this.message = message;\n  };\n});","map":{"version":3,"mappings":"AAAA,SAASA,gBAAgB,QAAQ,oBAAoB;AAoBrD,OAAO,IAAMC,aAAa,GAAsBD,gBAAgB,CAC9D,UAACE,MAAM;EACL,gBAASC,iBAAiB,CAAYC,OAAe;IACnDF,MAAM,CAAC,IAAI,CAAC;IACZ,IAAI,CAACG,IAAI,GAAG,eAAe;IAC3B,IAAI,CAACD,OAAO,GAAGA,OAAO;EACxB,CAAC;AAJD,CAIC,CACJ","names":["createErrorClass","SequenceError","_super","SequenceErrorImpl","message","name"],"sources":["C:\\Users\\Amali\\Desktop\\Building_the_IoT_w._P2P_and_Cloud_Computing\\IoTProject\\node_modules\\rxjs\\src\\internal\\util\\SequenceError.ts"],"sourcesContent":["import { createErrorClass } from './createErrorClass';\r\n\r\nexport interface SequenceError extends Error {}\r\n\r\nexport interface SequenceErrorCtor {\r\n  /**\r\n   * @deprecated Internal implementation detail. Do not construct error instances.\r\n   * Cannot be tagged as internal: https://github.com/ReactiveX/rxjs/issues/6269\r\n   */\r\n  new (message: string): SequenceError;\r\n}\r\n\r\n/**\r\n * An error thrown when something is wrong with the sequence of\r\n * values arriving on the observable.\r\n *\r\n * @see {@link operators/single}\r\n *\r\n * @class SequenceError\r\n */\r\nexport const SequenceError: SequenceErrorCtor = createErrorClass(\r\n  (_super) =>\r\n    function SequenceErrorImpl(this: any, message: string) {\r\n      _super(this);\r\n      this.name = 'SequenceError';\r\n      this.message = message;\r\n    }\r\n);\r\n"]},"metadata":{},"sourceType":"module"}